/*
 * Lilt REST API
 * The Lilt REST API enables programmatic access to the full-range of Lilt backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the Lilt CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests.  ## Authentication  Requests are authenticated via REST API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your REST API key as both the `username` and `password`.  For development, you may also pass the REST API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use.  ## Quotas  Our services have a general quota of 4000 requests per minute. Should you hit the maximum requests per minute, you will need to wait 60 seconds before you can send another request. 
 *
 * The version of the OpenAPI document: v2.0
 * Contact: support@lilt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lilt.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lilt.client.model.WorkflowStage;
import com.lilt.client.model.WorkflowTask;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Workflow metadata related to a document.
 */
@ApiModel(description = "Workflow metadata related to a document.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-11T00:19:44.343Z[GMT]")
public class DocumentWorkflow {
  public static final String SERIALIZED_NAME_DOCUMENT_ID = "documentId";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_ID)
  private Integer documentId;

  public static final String SERIALIZED_NAME_WORKFLOW_ID = "workflowId";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_ID)
  private Integer workflowId;

  public static final String SERIALIZED_NAME_STAGES = "stages";
  @SerializedName(SERIALIZED_NAME_STAGES)
  private List<WorkflowStage> stages = null;

  public static final String SERIALIZED_NAME_CURRENT_TASK = "currentTask";
  @SerializedName(SERIALIZED_NAME_CURRENT_TASK)
  private WorkflowTask currentTask;


  public DocumentWorkflow documentId(Integer documentId) {
    
    this.documentId = documentId;
    return this;
  }

   /**
   * Identifier of a document.
   * @return documentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12345", value = "Identifier of a document.")

  public Integer getDocumentId() {
    return documentId;
  }


  public void setDocumentId(Integer documentId) {
    this.documentId = documentId;
  }


  public DocumentWorkflow workflowId(Integer workflowId) {
    
    this.workflowId = workflowId;
    return this;
  }

   /**
   * Identifier for a Workflow that the document is using.
   * @return workflowId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1111", value = "Identifier for a Workflow that the document is using.")

  public Integer getWorkflowId() {
    return workflowId;
  }


  public void setWorkflowId(Integer workflowId) {
    this.workflowId = workflowId;
  }


  public DocumentWorkflow stages(List<WorkflowStage> stages) {
    
    this.stages = stages;
    return this;
  }

  public DocumentWorkflow addStagesItem(WorkflowStage stagesItem) {
    if (this.stages == null) {
      this.stages = new ArrayList<WorkflowStage>();
    }
    this.stages.add(stagesItem);
    return this;
  }

   /**
   * The stages in the document&#39;s workflow.
   * @return stages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The stages in the document's workflow.")

  public List<WorkflowStage> getStages() {
    return stages;
  }


  public void setStages(List<WorkflowStage> stages) {
    this.stages = stages;
  }


  public DocumentWorkflow currentTask(WorkflowTask currentTask) {
    
    this.currentTask = currentTask;
    return this;
  }

   /**
   * Get currentTask
   * @return currentTask
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WorkflowTask getCurrentTask() {
    return currentTask;
  }


  public void setCurrentTask(WorkflowTask currentTask) {
    this.currentTask = currentTask;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentWorkflow documentWorkflow = (DocumentWorkflow) o;
    return Objects.equals(this.documentId, documentWorkflow.documentId) &&
        Objects.equals(this.workflowId, documentWorkflow.workflowId) &&
        Objects.equals(this.stages, documentWorkflow.stages) &&
        Objects.equals(this.currentTask, documentWorkflow.currentTask);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, workflowId, stages, currentTask);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentWorkflow {\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    stages: ").append(toIndentedString(stages)).append("\n");
    sb.append("    currentTask: ").append(toIndentedString(currentTask)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

