/*
 * Lilt REST API
 * The Lilt REST API enables programmatic access to the full-range of Lilt backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the Lilt CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests. ## Authentication Requests are authenticated via REST API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your REST API key as both the `username` and `password`.  For development, you may also pass the REST API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use. 
 *
 * The version of the OpenAPI document: v2.0
 * Contact: support@lilt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lilt.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JobLeverageStatsProjects
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-20T00:13:26.792Z[GMT]")
public class JobLeverageStatsProjects {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_SOURCE_WORDS = "sourceWords";
  @SerializedName(SERIALIZED_NAME_SOURCE_WORDS)
  private Integer sourceWords;

  public static final String SERIALIZED_NAME_EXACT_WORDS = "exactWords";
  @SerializedName(SERIALIZED_NAME_EXACT_WORDS)
  private Integer exactWords;

  public static final String SERIALIZED_NAME_FUZZY_WORDS = "fuzzyWords";
  @SerializedName(SERIALIZED_NAME_FUZZY_WORDS)
  private Integer fuzzyWords;

  public static final String SERIALIZED_NAME_NEW_WORDS = "newWords";
  @SerializedName(SERIALIZED_NAME_NEW_WORDS)
  private Integer newWords;


  public JobLeverageStatsProjects id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The Project ID.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "The Project ID.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public JobLeverageStatsProjects sourceWords(Integer sourceWords) {
    
    this.sourceWords = sourceWords;
    return this;
  }

   /**
   * Total number of source words.
   * @return sourceWords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "Total number of source words.")

  public Integer getSourceWords() {
    return sourceWords;
  }


  public void setSourceWords(Integer sourceWords) {
    this.sourceWords = sourceWords;
  }


  public JobLeverageStatsProjects exactWords(Integer exactWords) {
    
    this.exactWords = exactWords;
    return this;
  }

   /**
   * Total number of exact words.
   * @return exactWords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "Total number of exact words.")

  public Integer getExactWords() {
    return exactWords;
  }


  public void setExactWords(Integer exactWords) {
    this.exactWords = exactWords;
  }


  public JobLeverageStatsProjects fuzzyWords(Integer fuzzyWords) {
    
    this.fuzzyWords = fuzzyWords;
    return this;
  }

   /**
   * Total number of fuzzy words.
   * @return fuzzyWords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "Total number of fuzzy words.")

  public Integer getFuzzyWords() {
    return fuzzyWords;
  }


  public void setFuzzyWords(Integer fuzzyWords) {
    this.fuzzyWords = fuzzyWords;
  }


  public JobLeverageStatsProjects newWords(Integer newWords) {
    
    this.newWords = newWords;
    return this;
  }

   /**
   * Total number of fuzzy words.
   * @return newWords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "Total number of fuzzy words.")

  public Integer getNewWords() {
    return newWords;
  }


  public void setNewWords(Integer newWords) {
    this.newWords = newWords;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobLeverageStatsProjects jobLeverageStatsProjects = (JobLeverageStatsProjects) o;
    return Objects.equals(this.id, jobLeverageStatsProjects.id) &&
        Objects.equals(this.sourceWords, jobLeverageStatsProjects.sourceWords) &&
        Objects.equals(this.exactWords, jobLeverageStatsProjects.exactWords) &&
        Objects.equals(this.fuzzyWords, jobLeverageStatsProjects.fuzzyWords) &&
        Objects.equals(this.newWords, jobLeverageStatsProjects.newWords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sourceWords, exactWords, fuzzyWords, newWords);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobLeverageStatsProjects {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceWords: ").append(toIndentedString(sourceWords)).append("\n");
    sb.append("    exactWords: ").append(toIndentedString(exactWords)).append("\n");
    sb.append("    fuzzyWords: ").append(toIndentedString(fuzzyWords)).append("\n");
    sb.append("    newWords: ").append(toIndentedString(newWords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

