/*
 * Lilt REST API
 * The Lilt REST API enables programmatic access to the full-range of Lilt backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the Lilt CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests.  ## Authentication  Requests are authenticated via REST API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your REST API key as both the `username` and `password`.  For development, you may also pass the REST API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use.  ## Quotas  Our services have a general quota of 4000 requests per minute. Should you hit the maximum requests per minute, you will need to wait 60 seconds before you can send another request. 
 *
 * The version of the OpenAPI document: v2.0
 * Contact: support@lilt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lilt.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Information about a document workflow task after it has moved a stage.
 */
@ApiModel(description = "Information about a document workflow task after it has moved a stage.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-11T00:19:44.343Z[GMT]")
public class NextWorkflowTask {
  /**
   * Identifier of the current workflow task.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    SUCCESS("SUCCESS"),
    
    WORKFLOW_FINISHED("WORKFLOW_FINISHED"),
    
    ALREADY_AT_START("ALREADY_AT_START"),
    
    INVALID_ARGUMENT("INVALID_ARGUMENT"),
    
    POSTCONDITIONS_FAILED("POSTCONDITIONS_FAILED"),
    
    UNKNOWN_ERROR("UNKNOWN_ERROR");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_NEW_TASK_ID = "newTaskId";
  @SerializedName(SERIALIZED_NAME_NEW_TASK_ID)
  private Integer newTaskId;

  public static final String SERIALIZED_NAME_NEW_STAGE_NAME = "newStageName";
  @SerializedName(SERIALIZED_NAME_NEW_STAGE_NAME)
  private String newStageName;


  public NextWorkflowTask status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Identifier of the current workflow task.
   * @return status
  **/
  @ApiModelProperty(example = "SUCCESS", required = true, value = "Identifier of the current workflow task.")

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public NextWorkflowTask newTaskId(Integer newTaskId) {
    
    this.newTaskId = newTaskId;
    return this;
  }

   /**
   * The identifier of the workflow task that is now currently active.
   * @return newTaskId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123", value = "The identifier of the workflow task that is now currently active.")

  public Integer getNewTaskId() {
    return newTaskId;
  }


  public void setNewTaskId(Integer newTaskId) {
    this.newTaskId = newTaskId;
  }


  public NextWorkflowTask newStageName(String newStageName) {
    
    this.newStageName = newStageName;
    return this;
  }

   /**
   * The name of the workflow task that is now currently active.
   * @return newStageName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Review", value = "The name of the workflow task that is now currently active.")

  public String getNewStageName() {
    return newStageName;
  }


  public void setNewStageName(String newStageName) {
    this.newStageName = newStageName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NextWorkflowTask nextWorkflowTask = (NextWorkflowTask) o;
    return Objects.equals(this.status, nextWorkflowTask.status) &&
        Objects.equals(this.newTaskId, nextWorkflowTask.newTaskId) &&
        Objects.equals(this.newStageName, nextWorkflowTask.newStageName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, newTaskId, newStageName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NextWorkflowTask {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    newTaskId: ").append(toIndentedString(newTaskId)).append("\n");
    sb.append("    newStageName: ").append(toIndentedString(newStageName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

