name: JUnit Tests

env:
  API_HOST: ${{ vars.API_HOST }}
  API_KEY: ${{ secrets.API_KEY }}

on:
  push:
    branches: [ master, openapi-bindings ]
  pull_request:
    branches: [ master, openapi-bindings ]

jobs:
  build:

    runs-on: gcp-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.1

      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: java
          service: lilt-java
          api_key: ${{ secrets.DD_API_KEY }}
          site: us5.datadoghq.com

      - name: Build
        run: mvn --batch-mode package
        env:
          DD_ENV: staging-tests
          DD_CIVISIBILITY_AGENTLESS_ENABLED: true
