name: JUnit Tests

env:
  API_HOST: ${{ vars.API_HOST }}
  API_KEY: ${{ secrets.API_KEY }}
  MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  MAVEN_CENTRAL_TOKEN: ${{ secrets.NEXUS_PASSWORD }}

on:
  push:
    branches: [ master, openapi-bindings ]
  pull_request:
    branches: [ master, openapi-bindings ]

jobs:
  build:

    runs-on: gcp-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.1

      - name: Build
        run: mvn -B package --file pom.xml

      - name: Publish
        run: mvn clean deploy -PsonatypeDeploy
