name: JUnit Tests

env:
  API_HOST: ${{ vars.API_HOST }}
  API_KEY: ${{ secrets.API_KEY }}

on:
  push:
    branches: [ master, openapi-bindings ]
  pull_request:
    branches: [ master, openapi-bindings ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.7
        uses: actions/setup-java@v4
        with:
          java-version: '7'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
