# This workflow will regenerate the client library API bindings based on the
# public OpenAPI spec.

name: OpenAPI Generator

on:
  workflow_dispatch:
  pull_request:
  repository_dispatch:
    types: [API-DocumentationV3-Deployment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: WyriHaximus/github-action-get-previous-tag@0.2.0
        id: latest
      - name: Generate API Bindings
        uses: docker://openapitools/openapi-generator-cli:v5.0.1
        with:
          args: >-
            generate
            -i https://developers.lilt.com/redocusaurus/plugin-redoc-0.yaml
            -p apiPackage=com.lilt.client.api
            -p artifactId=lilt-java
            -p artifactUrl=https://github.com/lilt/lilt-java
            -p developerEmail=nicholas.chiu@lilt.com
            -p developerName="Nicholas Chiu"
            -p developerOrganization="Lilt"
            -p developerOrganizationUrl=https://lilt.com
            -p groupId=com.lilt.client
            -g java
            -p licenseName="Lilt Client Library License"
            -p licenseUrl=license.md
            -p modelPackage=com.lilt.client.model
            -p packageVersion=${{ github.event.client_payload.version }}

            --skip-validate-spec
            -o .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.6
        with:
          token: ${{ secrets.GHA_REPO_DISPATCH_TOKEN }}
          commit-message: Regenerates API Bindings
          title: "OpenAPI: Regenerates API Bindings"
          body: |
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: openapi-bindings
          base: main
